// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUI-CUfwOh2Lh1PDZaK8KxRGtFiqgf0DA',
    appId: '1:305290585380:web:16ee0acf856e64c2b33fb1',
    messagingSenderId: '305290585380',
    projectId: 'grouplocatorapp-ccd18',
    authDomain: 'grouplocatorapp-ccd18.firebaseapp.com',
    storageBucket: 'grouplocatorapp-ccd18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzb_pU9IJu6xeWB3GPljTwD_TreVWENRA',
    appId: '1:305290585380:android:3060869b6ea288cfb33fb1',
    messagingSenderId: '305290585380',
    projectId: 'grouplocatorapp-ccd18',
    storageBucket: 'grouplocatorapp-ccd18.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUI-CUfwOh2Lh1PDZaK8KxRGtFiqgf0DA',
    appId: '1:305290585380:web:c663be9b509adda0b33fb1',
    messagingSenderId: '305290585380',
    projectId: 'grouplocatorapp-ccd18',
    authDomain: 'grouplocatorapp-ccd18.firebaseapp.com',
    storageBucket: 'grouplocatorapp-ccd18.firebasestorage.app',
  );
}
